apiVersion: v1
kind: Service
metadata:
  name: sec-spring-boot-app-svc
spec:
  selector:
    app: sec-spring-boot-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
